### ISSUE TITLE
Add auto-stubbed tags configuration

### ISSUE THREAD

**Issue by jonathanwiesel** [no-stack-dub-sack/apexdox-vs-code#59] opened 2022-10-18 14:06 UTC
It would be great to be able to configure which tags to span when auto-stubbing.

For example, we do not use the author and date tags to avoid redundancy with VCS info so we would like to avoid those being automatically generated

**Comment by no-stack-dub-sack** [comment] 2022-11-27 16:59
Thanks for the request! Closing as a dupe of #50. This shouldn't be too hard to implement, I just need to find the time. Hopefully I can get to this soon, but open to a PR in the meantime if anyone is interested in taking this on.

**Closed by no-stack-dub-sack** 2022-11-27 16:59 UTC
